name: Deploy React App with GitHub Pages

on:
  push:
    branches: ["main"]  # Trigger on pushes to the main branch
  workflow_dispatch:  # Allows for manual triggering

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build React app
        run: npm run build:react
      - name: Bundle the app with Webpack
        run: npm run build:bundle
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: react-build
          path: ./build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages  
          publish_dir: ./build  
      - name: Debug URL Output
        run: echo "Deployed to GitHub Pages: ${{ steps.deployment.outputs.page_url }}"
