name: Deploy React App to GitHub Pages

on:
  push:
    branches: ["main"]  # Deploy only when the main branch is updated
  workflow_dispatch:     # Allows manual runs
  
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Build React App
        run: npm run build:react  # Only build the React app

      - name: Clean Up Build Directory
        run: |
          find build -type l -delete
          find build -name '*.map' -delete
          find build -size +500M -delete

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
